Repository Devcourse-BE6-8-2-Team5/Backend, pull requests merged in 2025-08, with the labels that each got.

#175 [refactor] 3개의 퀴즈를 풀면 반환 하는 데이터 추가 #1
  src/main/java/com/back/domain/member/quizhistory/entity/QuizHistory.java
  src/main/java/com/back/domain/member/quizhistory/repository/QuizHistoryRepository.java
  src/main/java/com/back/domain/quiz/daily/controller/DailyQuizController.java
  src/main/java/com/back/domain/quiz/daily/dto/DailyQuizWithHistoryDto.java
  src/main/java/com/back/domain/quiz/daily/service/DailyQuizService.java
  src/main/java/com/back/domain/quiz/detail/controller/DetailQuizController.java
  src/main/java/com/back/domain/quiz/detail/dto/DetailQuizWithHistoryDto.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizService.java
  src/main/java/com/back/domain/quiz/fact/controller/FactQuizController.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizWithHistoryDto.java
  src/main/java/com/back/domain/quiz/fact/service/FactQuizService.java
Labels: refactor

#183 [feat]: 경험치순 회원정보조회 기능 구현 #1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/dto/MemberWithRankDto.java
  src/main/java/com/back/domain/member/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/init/DevInitData.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: feat

#197 [fix] 상세 퀴즈 생성 로직 수정
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
Labels: fix

#199 [feat] 뉴스 조회시 오늘의 뉴스, ox퀴즈용 뉴스 조회 안되도록 변경
  src/main/java/com/back/domain/news/common/test/controller/TestController.java
  src/main/java/com/back/domain/news/real/controller/RealNewsController.java
  src/main/java/com/back/domain/news/real/repository/RealNewsRepository.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/domain/news/real/service/RealNewsService.java
  src/main/java/com/back/domain/quiz/fact/service/FactQuizService.java
  src/main/resources/application.yml
Labels: feat

#213 [fix] proxy와 entity manger 활용하여 1대1매핑 영속성 문제 해결
  src/main/java/com/back/domain/news/common/test/controller/TestController.java
  src/main/java/com/back/domain/news/fake/entity/FakeNews.java
  src/main/java/com/back/domain/news/fake/service/FakeNewsService.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/global/ai/processor/FakeNewsGeneratorProcessor.java
  src/main/resources/application.yml
Labels: fix

#237 [chore] 배포 CORS 설정
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: chore

#245 [Refactor] redirect-uri 수정
  src/main/resources/application.yml
Labels: refactor

#247 [feat] 스케줄러 keep alive 도입
  build.gradle
  src/main/java/com/back/dev/controller/DevTestController.java
  src/main/java/com/back/dev/service/DevTestNewsService.java
  src/main/java/com/back/domain/news/fake/service/AdminFakeNewsService.java
  src/main/java/com/back/domain/news/real/controller/AdminNewsController.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/global/appconfig/SchedulerConfig.java
  src/main/java/com/back/global/controller/HealthController.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#249 fix:스케줄러 시간바꿔서 테스트
  src/main/java/com/back/domain/news/fake/service/AdminFakeNewsService.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
Labels: fix

#258 [feat] 뉴스 테이블 인덱스 도입
  fly.toml
  src/main/java/com/back/domain/news/real/controller/AdminNewsController.java
  src/main/java/com/back/domain/news/real/entity/RealNews.java
  src/main/java/com/back/domain/news/real/repository/RealNewsRepository.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/domain/news/real/service/RealNewsService.java
  src/main/resources/application-prod.yml
Labels: feat

#261 [feat] keepalive 모니터링 도입 및 github action으로 외부핑
  .github/workflows/wakeup-scheduler.yml
  src/main/java/com/back/domain/news/common/service/KeepAliveMonitoringService.java
  src/main/java/com/back/domain/news/fake/service/AdminFakeNewsService.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/domain/news/real/service/NewsAnalysisService.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/global/async/AsyncConfig.java
  src/main/resources/application.yml
Labels: feat
