Repository Devcourse-BE6-8-2-Team5/Backend, pull requests merged in 2025-07, with the labels that each got.

#34 [FEAT] SpringDoc 설정 #1
  build.gradle
  src/main/java/com/back/global/springdoc/SpringDocConfig.java
Labels: feat

#35 [FEAT] 진짜뉴스 Entity 생성#1
  src/main/java/com/back/domain/news/realNews/entity/RealNews.java
Labels: feat

#41 [refactor] ServiceException처리 #1
  src/main/java/com/back/global/springdoc/exception/ServiceException.java
  src/main/java/com/back/global/springdoc/globalExceptionHandler/GlobalExceptionHandler.java
Labels: refactor

#42 [feat]: User Entity 구현#1
  src/main/java/com/back/domain/user/entity/User.java
Labels: feat

#46 [refactor] : exception 처리 클래스 디렉토리 구조변경 #1
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
Labels: refactor

#49 feat : 네이버 뉴스 기사만 필터링 하도록 변경
  src/main/java/com/back/domain/news/realNews/service/RealNewsService.java
Labels: feat

#53 [feat] 유저 추가(회원가입) 구현#1
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/MemberDto.java
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/service/MemberService.java
Labels: feat

#54 [feat] : 회원 로그인 구현#1
  src/main/java/com/back/domain/member/controller/MemberController.java
Labels: feat

#57 [feat] 페이징 처리를 위한 ServiceUtil 도입 및 제목포함, 날짜순 다건 조회 구현#1
  src/main/java/com/back/domain/news/realNews/controller/RealNewsController.java
  src/main/java/com/back/domain/news/realNews/repository/RealNewsRepository.java
  src/main/java/com/back/domain/news/realNews/service/RealNewsService.java
  src/main/java/com/back/domain/news/util/NewsPageService.java
  src/main/java/com/back/domain/news/util/NewsType.java
Labels: feat

#59 [feat] : 회원정보 수정#1
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/service/MemberService.java
Labels: feat

#60 [feat] 진짜 뉴스 삭제 기능 #1
  src/main/java/com/back/domain/news/realNews/controller/RealNewsController.java
  src/main/java/com/back/domain/news/realNews/entity/RealNews.java
  src/main/java/com/back/domain/news/realNews/service/RealNewsService.java
Labels: feat

#65 [feat] 가짜 뉴스 엔티티 생성 및 진짜 뉴스 카테고리 도입#1
  src/main/java/com/back/domain/news/fakeNews/entity/FakeNews.java
  src/main/java/com/back/domain/news/realNews/entity/RealNews.java
  src/main/java/com/back/domain/news/util/NewsCategory.java
Labels: feat

#71 [feat] 상세 퀴즈 수정 구현#1
  src/main/java/com/back/domain/quiz/detail/controller/DetailQuizController.java
  src/main/java/com/back/domain/quiz/detail/dto/DetailQuizDto.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizService.java
Labels: feat

#72 [Feat] Spring Security 인증/인가
  .gitignore
  build.gradle
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/dto/MemberWithAuthDto.java
  src/main/java/com/back/domain/member/dto/MemberWithInfoDto.java
  src/main/java/com/back/domain/member/entity/Member.java
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/service/AuthTokenService.java
  src/main/java/com/back/domain/member/service/MemberService.java
  src/main/java/com/back/global/appconfig/AppConfig.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/rsData/RsData.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/java/com/back/global/standard/util/Ut.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/back/backend/BackendApplicationTests.java
  src/test/java/com/back/backend/domain/member/controller/MemberControllerTest.java
Labels: enhancement

#75 [feat] RealNews 엔티티 수정 및 상세 퀴즈 생성 구현#1
  src/main/java/com/back/BackendApplication.java
  src/main/java/com/back/domain/news/realNews/entity/RealNews.java
  src/main/java/com/back/domain/news/realNews/repository/RealNewsRepository.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizScheduledService.java
Labels: feat

#79 [feat] 퀴즈 타입 추가
  src/main/java/com/back/domain/quiz/QuizType.java
  src/main/java/com/back/domain/quiz/detail/entity/DetailQuiz.java
  src/main/java/com/back/domain/quiz/fact/entity/FactQuiz.java
Labels: feat

#82 [feat] TodayNews 엔티티 생성
  src/main/java/com/back/domain/news/common/dto/NaverNewsDto.java
  src/main/java/com/back/domain/news/common/dto/NewsDetailDto.java
  src/main/java/com/back/domain/news/common/entity/KeywordHistory.java
  src/main/java/com/back/domain/news/common/enums/NewsCategory.java
  src/main/java/com/back/domain/news/common/enums/NewsType.java
  src/main/java/com/back/domain/news/common/service/KeywordHistoryService.java
  src/main/java/com/back/domain/news/common/service/NewsPageService.java
  src/main/java/com/back/domain/news/fake/entity/FakeNews.java
  src/main/java/com/back/domain/news/real/controller/RealNewsController.java
  src/main/java/com/back/domain/news/real/dto/RealNewsDto.java
  src/main/java/com/back/domain/news/real/entity/RealNews.java
  src/main/java/com/back/domain/news/real/repository/RealNewsRepository.java
  src/main/java/com/back/domain/news/real/service/RealNewsService.java
  src/main/java/com/back/domain/news/today/entity/TodayNews.java
  src/main/java/com/back/domain/quiz/detail/entity/DetailQuiz.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizScheduledService.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizService.java
Labels: feat

#89 [feat] 팩트 체크 퀴즈 조회 api 구현
  src/main/java/com/back/domain/news/fake/entity/FakeNews.java
  src/main/java/com/back/domain/quiz/fact/controller/FactQuizController.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDto.java
  src/main/java/com/back/domain/quiz/fact/dto/FactQuizDtoWithNewsContent.java
  src/main/java/com/back/domain/quiz/fact/repository/FactQuizRepository.java
  src/main/java/com/back/domain/quiz/fact/service/FactQuizService.java
Labels: feat

#94 [feat] 유저 정답지 생성 다건조회 기능 구현 #1
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/quizhistory/controller/QuizHistoryController.java
  src/main/java/com/back/domain/member/quizhistory/dto/QuizHistoryDto.java
  src/main/java/com/back/domain/member/quizhistory/entity/QuizHistory.java
  src/main/java/com/back/domain/member/quizhistory/repository/QuizHistoryRepository.java
  src/main/java/com/back/domain/member/quizhistory/service/QuizHistoryService.java
Labels: feat

#100 [feat] : InitData 생성 멤버만 #1
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/init/DevInitData.java
Labels: feat

#97 [feat] realNewsDto 구조 변경 및 오늘의 뉴스 조회 기능 구현
  src/main/java/com/back/domain/news/real/controller/RealNewsController.java
  src/main/java/com/back/domain/news/real/dto/RealNewsDto.java
  src/main/java/com/back/domain/news/real/mapper/RealNewsMapper.java
  src/main/java/com/back/domain/news/real/repository/RealNewsRepository.java
  src/main/java/com/back/domain/news/real/repository/TodayNewsRepository.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/domain/news/real/service/RealNewsService.java
  src/main/java/com/back/domain/news/today/entity/TodayNews.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: feat

#103 [feat] 오늘의 퀴즈 생성 로직 구현#1
  src/main/java/com/back/domain/news/real/repository/TodayNewsRepository.java
  src/main/java/com/back/domain/quiz/daily/controller/DailyQuizController.java
  src/main/java/com/back/domain/quiz/daily/repository/DailyQuizRepository.java
  src/main/java/com/back/domain/quiz/daily/service/DailyQuizService.java
Labels: feat

#108 [chore] 퀴즈 도메인 api 문서 작성
  src/main/java/com/back/domain/quiz/daily/controller/DailyQuizController.java
  src/main/java/com/back/domain/quiz/daily/service/DailyQuizService.java
  src/main/java/com/back/domain/quiz/detail/controller/DetailQuizController.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizService.java
  src/main/java/com/back/domain/quiz/fact/controller/FactQuizController.java
Labels: chore

#113 [chore] 뉴스 컨트롤러 api 문서 작성
  src/main/java/com/back/domain/news/real/controller/AdminNewsController.java
  src/main/java/com/back/domain/news/real/controller/RealNewsController.java
Labels: chore

#116 refactor : initData 날짜 수정 및 fakeNews 생성 파싱 문제 해결
  src/main/java/com/back/global/ai/processor/FakeNewsGeneratorProcessor.java
  src/main/java/com/back/global/init/DevInitData.java
Labels: refactor

#119 [feat] InitData에 퀴즈 데이터 추가
  src/main/java/com/back/domain/quiz/daily/service/DailyQuizService.java
  src/main/java/com/back/domain/quiz/detail/service/DetailQuizService.java
  src/main/java/com/back/domain/quiz/fact/service/FactQuizService.java
  src/main/java/com/back/global/init/DevInitData.java
Labels: feat

#129 [feat] DevInitData 수정
  src/main/java/com/back/global/init/DevInitData.java
Labels: feat

#133 [Feat] 구글로그인, 네이버로그인 완료
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/global/security/CustomOAuth2UserService.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/resources/application.yml
Labels: feat

#138 [Feat] 소셜로그인 추가 기능 구현
  src/main/java/com/back/domain/member/member/dto/MemberWithAuthDto.java
  src/main/java/com/back/domain/member/member/dto/MemberWithInfoDto.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/CustomOAuth2LoginSuccessHandler.java
Labels: feat

#145 [fix]initData 오류 수정
  src/main/java/com/back/domain/quiz/detail/dto/DetailQuizDto.java
Labels: fix

#151 [feat] : 가짜 뉴스 스케줄러 기능 구현
  src/main/java/com/back/domain/news/common/test/controller/TestController.java
  src/main/java/com/back/domain/news/fake/service/AdminFakeNewsService.java
  src/main/java/com/back/domain/news/real/controller/AdminNewsController.java
  src/main/java/com/back/domain/news/real/entity/RealNews.java
  src/main/java/com/back/domain/news/real/service/AdminNewsService.java
  src/main/java/com/back/domain/news/real/service/NewsDataService.java
  src/main/java/com/back/domain/news/real/service/RealNewsService.java
  src/main/resources/application.yml
Labels: feat

#154 [feat] DetailQuizControllerTest 작성
  src/main/java/com/back/global/init/TestInitData.java
  src/test/java/com/back/backend/domain/quiz/detail/controller/DetailQuizControllerTest.java
  src/test/java/com/back/backend/global/config/TestRqConfig.java
  src/test/java/com/back/backend/global/rq/TestRq.java
Labels: feat

#157 [chore] 퀴즈 도메인 API 문서 수정
  src/main/java/com/back/domain/quiz/daily/controller/DailyQuizController.java
  src/main/java/com/back/domain/quiz/detail/controller/DetailQuizController.java
  src/main/java/com/back/domain/quiz/fact/controller/FactQuizController.java
Labels: chore

#160 [feat] 팩트 퀴즈 테스트 코드 작성#1
  src/test/java/com/back/backend/domain/quiz/fact/controller/FactQuizControllerTest.java
Labels: feat

#166 [Feat] 시큐리티 경로 제한 수정 완료
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: feat

#172 [Feat] 시큐리티 swagger , h2 경로 제한 수정 완료
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/SecurityConfig.java
Labels: feat
